echo "　 　　_,,　iヽ---、／i"
echo "　　<,´　　　　　　 i　ヽ"
echo "　　ノイ＼レレ／ゝiノ、"
echo "　　｀ ﾉiｲO 　 Oｱﾚi＼ノ"
echo "　 　 iﾉヽ" － "ノﾙノλ"
echo "　　（＼イヽ￣ノ/ ヽ　／）"
echo "　　　 （_,i_,_￣_, iゝ_,_,） <　))"
echo "　　　/　/ ´￣｀｀ ヽ、ヽ、)"
echo "　　 (u./　　　　　 　ヽuノ"
echo "　　　 ﾉ∧∧∧∧∧ヽ"
echo "　　　｀～Ｔヽ～、～´"
echo "　　　　　 し　 　ヽノ"
echo "     ⑨、バカ 不太聪明的亚子"